# Generated by Django 3.1.2 on 2020-10-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_userrequest_initiatedtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userRequest',
        ),
    ]
