# Generated by Django 3.1.2 on 2020-10-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_userrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hitchHikeRequest',
        ),
    ]
